.TH apol 1
.SH NAME
apol \- SELinux policy analysis tool
.SH SYNOPSIS
.B apol
[OPTIONS] [POLICY ...]
.SH DESCRIPTION
.PP
.B apol 
is a graphical tool that allows the user to inspect aspects of a SELinux policy.
The tool allows the user to browse policy components (types, classes, roles, users, etc.), rules (TE, RBAC, MLS), and file system contexts.
The tool also provides in depth analyses of domain transitions, information flows, and relabeling permissions.
.SH POLICY
.PP
.B 
apol
supports loading a SELinux policy in one of three formats. 
.IP "source"
A single text file containing policy source for versions 12 through 21. This file is usually named policy.conf.
.IP "binary"
A single file containg a monolithic kernel binary policy for versions 15 through 21. This file is usually named by version - for example, policy.20.
.IP "modular"
A list of policy packages each containing a loadable policy module. The first module listed must be a base module.
.PP
If not provied
.B
apol
will begin with no policy loaded.
.SH OPTIONS
.IP "-v, --version"
Print version information and exit.
.IP "-h, --help"
Print help information and exit.
.SH AUTHOR
This manual page was written by Jeremy A. Mowery <jmowery@tresys.com>.  
.SH COPYRIGHT
Copyright(C) 2001-2007 Tresys Technology, LLC
.SH SEE ALSO
seinfo(1), sesearch(1), sechecker(1), indexcon(1), searchcon(1)
