.TH apol 1
.SH NAME
apol \- SELinux policy analysis tool
.SH SYNOPSIS
.B apol
[OPTIONS] [POLICY ...]
.SH DESCRIPTION
.PP
.B apol 
is a graphical tool that allows the user to inspect aspects of a SELinux security policy.  The tool lets the user browse policy components (types, classes, roles, users, etc.), rules (TE, RBAC, MLS), and file system contexts. Among other capabilities, the tool provides in depth analyses of domain transitions, information flows, and relabeling permissions.
.SH OPTIONS
.IP "FILE"
open policy file named FILE
.IP "-v, --version"
display version information
.IP "-h, --help"
display help dialog
.SH AUTHOR
This manual page was written by Kevin Carr <kcarr@tresys.com>.  
.SH COPYRIGHT
Copyright(C) 2006 Tresys Technology, LLC
.SH SEE ALSO
seinfo(1), sesearch(1), sechecker(1), indexcon(1)
