.TH findcon 1
.SH NAME
findcon \- SELinux file context search tool
.SH SYNOPSIS
.B findcon
[OPTIONS] -c CONTEXT FILENAMES
.SH DESCRIPTION
.PP
.B findcon
allows the user to search for files with a specified context.
Results can be filtered by object class as described below.
.SH OPTIONS
.IP "-c, --context=CONTEXT"
Search for files with context CONTEXT.
A context is specified as a colon separated list of user, role, and type as follows: user_u:object_r:type_t.
If the system supports MLS, additional MLS range can be added to the end as follows: user_u:object_r:type_t:s0.
If a field is not specified, the query will always match that field.
If the system supports MLS and the translation library is enabled, matching is done using translated contexts.
To match raw contexts, use the --raw option.
The special string "unlabeled" can also be specified to match files with no label.
.IP "--raw"
Match raw contexts, ignoring the translation library if present.
.IP "-o, --object=OBJECT"
Restrict search to files of object class OBJECT.
.IP "-r, --recursive"
Recurse through directories.
.IP "-s, --stdin"
Read FILENAMES from standard input.
.IP "-q, --quiet"
Suppress progress output.
.IP "-v, --verbose"
Display context info.
.IP "-h, --help"
Print help information and exit.
.IP "-V, --version"
Print version information and exit.
.SH INFORMATION
Valid object classes are
.PP
file,
dir,
lnk_file,
chr_file,
blk_file,
sock_file,
fifo_file
.SH EXAMPLES
.TP
.B findcon -c : .
Find every context in the current directory.
.TP
.B findcon -c user_u: .
Find every context in the current directory whose user is user_u.
.TP
.B findcon -r -c ::type_t:s0 .
Find every context with type type_t and MLS range s0, searching in the
current directory and all subdirectories.
.SH AUTHOR
This manual page was written by Jeremy A. Mowery <jmowery@tresys.com>.
.SH COPYRIGHT
Copyright(C) 2003-2007 Tresys Technology, LLC
.SH BUGS
Please report bugs via an email to setools-bugs@tresys.com.
.SH SEE ALSO
replcon(1), indexcon(1), searchcon(1)
