.TH indexcon 1
.SH NAME
indexcon \- SELinux file context indexing tool
.SH SYNOPSIS
.B indexcon
<filename> [OPTIONS]
.SH DESCRIPTION
This manual page describes the
.BR indexcon
command.
.PP
.B indexcon 
allows the user to index the file contexts on a SELinux system.  The results can be imported in the apol analysis tool or searched using the searchcon tool.
.SH OPTIONS
.IP "-d directory, --directory=directory"
Start scanning a directory
.IP "-h, --help"
Display help information and exit
.IP "-v, --version"
Display version information and exit
.SH AUTHOR
This manual page was written by Kevin Carr <kcarr@tresys.com>.  
.SH COPYRIGHT
Copyright(C) 2006 Tresys Technology, LLC
.SH SEE ALSO
findcon(1), replcon(1), searchcon(1), apol(1)
