.TH replcon 1
.SH NAME
replcon \- SELinux file context replacement tool
.SH SYNOPSIS
.B replcon
[OPTIONS] -c OLD NEW FILENAMES
.SH DESCRIPTION
.PP
.B replcon
allows the user to find and replace file contexts.
Replacements can be restricted by object class.
.SH OPTIONS
.IP "-c, --context=OLD NEW"
Search for files with context OLD and replace their context with NEW.
A context is specified as a colon separated list of user, role, and type as follows: user_u:object_r:type_t.
If the system supports MLS, additional MLS range can be added to the end as follows: user_u:object_r:type_t:s0.
If a field is not specified, the query will always match that field.
If the system supports MLS and the translation library is enabled, matching is done using translated contexts.
To match raw contexts, use the --raw option.
The special string "unlabeled" can also be specified to match files with no label.
.IP "--raw"
Match raw contexts, ignoring the translation library if present.
.IP "-o, --object=OBJECT"
Only replace the context for files of object class OBJECT.
.IP "-r, --recursive"
Recurse through directories.
.IP "-s, --stdin"
Read FILENAMES from standard input.
.IP "-q, --quiet"
Suppress progress output.
.IP "-V, --verbose"
Display context info.
.IP "-v, --version"
Print version information and exit.
.IP "-h, --help"
Print help information and exit.
.SH INFORMATION
Valid object classes are
.PP
file,
dir,
lnk_file,
chr_file,
blk_file,
sock_file,
fifo_file
.SH EXAMPLES
.TP
.B replcon -c : ::type_t .
Replace every context in the current directory with type_t.
.TP
.B replcon -c user_u: :role_r .
Replace every context with user user_u in the current directory with role role_r.
.TP
.B replcon -c ::type_t:s0  :::s0:c0 .
Replace every context with type type_t and MLS range s0 in the current directory with MLS range s0:c0.
.SH AUTHOR
This manual page was written by Jeremy A. Mowery <jmowery@tresys.com>.
.SH COPYRIGHT
Copyright(C) 2003-2007 Tresys Technology, LLC
.SH BUGS
Please report bugs via an email to setools-bugs@tresys.com.
.SH SEE ALSO
findcon(1), indexcon(1), searchcon(1)
