.TH seaudit-report 8
.SH NAME
seaudit-report \- SELinux audit log reporting tool
.SH SYNOPSIS
.B seaudit-report
[OPTIONS] LOGFILES
.SH DESCRIPTION
This manual page describes the
.B seaudit-report
command.
.PP
.B seaudit-report
allows the user to generate custom audit log reports from the command line or by integration with the Logwatch tool.
.SH OPTIONS
.IP "-s, --stdin"
Read LOGFILES from standard input.
.IP "-m, --malformed"
Include malformed log messages.
.IP "-oFILE, --output=FILE"
Output to file.
.IP "-cFILE, --config=FILE"
Use alternate config file.
.IP "--html"
Set output format to HTML.  Default is plain text.
.IP "--stylesheet=FILE"
HTML stylesheet for formatting HTML report.  This option is ignored if
--html is not given.  See /usr/local/share/setools/seaudit-report.css
(or wherever you installed SETools) for an example stylesheet.
.IP "-v, --version"
Display version information and exit.
.IP "-h, --help"
Display this help and exit.
.SH AUTHOR
This manual page was written by Kevin Carr <kcarr@tresys.com>.  
.SH COPYRIGHT
Copyright(C) 2006 Tresys Technology, LLC
.SH SEE ALSO
seaudit(8)
