.TH sediff 1
.SH NAME
sediff \- SELinux policy difference tool
.SH SYNOPSIS
.B sediff
[OPTIONS] ORIGINAL_POLICY MODIFIED_POLICY
.SH DESCRIPTION
.PP
.B sediff
allows the user to inspect the semantic differences between two SELinux policy files.
The policies can be either source or binary policy files, version 15 or later.
By default, all supported policy elements are examined.
.SH OPTIONS
.IP "-c, --classes"
object class and common permission definitions
.IP "-t, --types"
type definitions
.IP "-a, --attributes"
attribute definitions
.IP "-r, --roles"
role definitions
.IP "-u, --users"
user definitions
.IP "-b, --booleans"
boolean definitions and default values
.IP "-T, --terules"
type enforcement rules
.IP "-R, --roletrans"
role transition rules
.IP "-A, --roleallows"
role allow rules
.IP "-q, --quiet"
only print different definitions
.IP "-s, --stats"
print useful policy statistics
.IP "-h, --help"
display this help and exit
.IP "-v, --version"
output version information and exit
.SH AUTHOR
This manual page was written by Kevin Carr <kcarr@tresys.com>.
.SH COPYRIGHT
Copyright(C) 2006 Tresys Technology, LLC
.SH SEE ALSO
sediffx(1)
