.TH sesearch 1
.SH NAME
sesearch \- SELinux policy query tool
.SH SYNOPSIS
.B sesearch
[OPTIONS] [POLICY_FILE]
.SH DESCRIPTION
.PP
.B sesearch
allows the user to query an SELinux policy for type enforcement rules.
.SH OPTIONS
.IP "-s NAME, --source NAME"
find rules with NAME type/attrib (regex) as source
.IP "-t NAME, --target NAME"
find rules with NAME type/attrib (regex) as target
.IP "--role_source NAME"
find rules with NAME role (regex) as source
.IP "--role_target NAME"
find rules with NAME role (regex) as target
.IP "-c NAME, --class NAME"
find rules with NAME as the object class
.IP "-p P1[,P2,...] --perms P1[,P2...]"
find rules with the specified permissions
.IP "-b NAME, --boolean NAME"
find conditional rules with NAME in the expression
.IP "--allow"
search for allow rules
.IP "--neverallow"
search for neverallow rules
.IP "--audit"
search for auditallow and dontaudit rules
.IP "--type"
search for type_trans, type_member, and type_change rules
.IP "--rangetrans"
search for range transition rules
.IP "--role_allow"
search for role allow rules
.IP "--role_trans"
search for role transition rules
.IP "-a, --all"
show all rules regardless of type, class, or permissions
.IP "-i, --indirect"
also search for the type's attributes
.IP "-n, --noregex"
do not use regular expression to match type/attributes
.IP "-l, --lineno"
include line number in policy.conf for each rule.  This option is
ignored if using a binary policy.
.IP "-C, --show_cond"
show conditional expression for conditional rules
.IP "-h, --help"
display this help and exit
.IP "-v, --version"
output version information and exit
.SH INFORMATION
If none of -s, -t, -c, -p, -b, --role_source, or --role_target
are specified, then all rules are shown.
You must specify -a (--all), or one of more of --allow, --neverallow,
--audit, --rangetrans, --role_allow, --role_trans or --type.
.PP
If no policy file name is provided, the default source policy will be loaded.
If that is not available, the default binary policy will be loaded.
.SH AUTHOR
This manual page was written by Kevin Carr <kcarr@tresys.com>.  
.SH COPYRIGHT
Copyright(C) 2006 Tresys Technology, LLC
.SH BUGS
Please report bugs via an email to setools-bugs@tresys.com.
.SH SEE ALSO
seinfo(1), apol(1)
