.TH findcon 1
.SH NAME
findcon \- File context search tool for Security Enhanced Linux.
.SH SYNOPSIS
.B findcon
[OPTIONS] -c CONTEXT FILENAMES
.SH DESCRIPTION
.B findcon 
allows users, running Security Enhanced Linux, to search file systems 
for files of a specified context. Results can be filtered by object type. 
.B findcon 
provides the ability to recurse through directories as 
well as to read filenames from standard input.
.SH OPTIONS
.TP
\-c, \-\-context=CONTEXT
Specify context to search for.  A context may be specified as a colon 
separated list of user, role, and type as follows - user_u:object_r:user_t. 
The tool will automatically match a user, role, or type that is not specified, 
with any other user, role, or type.  For example ::user_t specifies any context 
that has user_t as the type.
.TP
\-o, \-\-object=OBJECT
Restrict search to the specified object class.  The valid object classes are 
file, dir, lnk_file, chr_file, blk_file, sock_file, fifo_file, all_files
.TP
\-r, \-\-recursive
Recurse through directories.
.TP
\-s, \-\-stdin
Read FILENAMES from standard input.
.TP
\-q, \-\-quiet
Supress progress output.
.TP
\-V, \-\-verbose
Display context info.
.TP
\-v, \-\-version
Display version information and exit.
.TP
\-h, \-\-help
Display help information and exit.

.SH AUTHOR
Copyright(C) 2003-2005 Tresys Technology, LLC
.SH SEE ALSO
replcon(1), searchcon(1), indexcon(1), seinfo(1), sesearch(1), sediff(1), 
sechecker(1), seaudit-report(1), sediffx(1), seaudit(1), apol(1)  
