/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_window1 (void)
{
  GtkWidget *window1;
  GtkWidget *vbox1;
  GtkWidget *menubar2;
  GtkWidget *menuitem5;
  GtkWidget *menuitem5_menu;
  GtkWidget *Run_Diff;
  GtkWidget *Exit;
  GtkWidget *menuitem8;
  GtkWidget *menuitem8_menu;
  GtkWidget *Help;
  GtkWidget *about;
  GtkWidget *notebook2;
  GtkWidget *hbox1;
  GtkWidget *scrolledwindow8;
  GtkWidget *treeview1;
  GtkWidget *scrolledwindow7;
  GtkWidget *textview7;
  GtkWidget *label7;
  GtkWidget *scrolledwindow4;
  GtkWidget *textview4;
  GtkWidget *label8;
  GtkWidget *scrolledwindow5;
  GtkWidget *textview5;
  GtkWidget *label9;
  GtkWidget *scrolledwindow6;
  GtkWidget *textview6;
  GtkWidget *label10;
  GtkAccelGroup *accel_group;

  accel_group = gtk_accel_group_new ();

  window1 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window1), _("Sediff"));
  gtk_window_set_default_size (GTK_WINDOW (window1), 700, 490);

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox1);
  gtk_container_add (GTK_CONTAINER (window1), vbox1);

  menubar2 = gtk_menu_bar_new ();
  gtk_widget_show (menubar2);
  gtk_box_pack_start (GTK_BOX (vbox1), menubar2, FALSE, FALSE, 0);

  menuitem5 = gtk_menu_item_new_with_mnemonic (_("_File"));
  gtk_widget_show (menuitem5);
  gtk_container_add (GTK_CONTAINER (menubar2), menuitem5);

  menuitem5_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuitem5), menuitem5_menu);

  Run_Diff = gtk_image_menu_item_new_from_stock ("gtk-open", accel_group);
  gtk_widget_show (Run_Diff);
  gtk_container_add (GTK_CONTAINER (menuitem5_menu), Run_Diff);

  Exit = gtk_image_menu_item_new_from_stock ("gtk-quit", accel_group);
  gtk_widget_show (Exit);
  gtk_container_add (GTK_CONTAINER (menuitem5_menu), Exit);

  menuitem8 = gtk_menu_item_new_with_mnemonic (_("_Help"));
  gtk_widget_show (menuitem8);
  gtk_container_add (GTK_CONTAINER (menubar2), menuitem8);

  menuitem8_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuitem8), menuitem8_menu);

  Help = gtk_image_menu_item_new_from_stock ("gtk-help", accel_group);
  gtk_widget_show (Help);
  gtk_container_add (GTK_CONTAINER (menuitem8_menu), Help);

  about = gtk_menu_item_new_with_mnemonic (_("About"));
  gtk_widget_show (about);
  gtk_container_add (GTK_CONTAINER (menuitem8_menu), about);

  notebook2 = gtk_notebook_new ();
  gtk_widget_show (notebook2);
  gtk_box_pack_start (GTK_BOX (vbox1), notebook2, TRUE, TRUE, 0);

  hbox1 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (notebook2), hbox1);

  scrolledwindow8 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow8);
  gtk_box_pack_start (GTK_BOX (hbox1), scrolledwindow8, TRUE, TRUE, 0);

  treeview1 = gtk_tree_view_new ();
  gtk_widget_show (treeview1);
  gtk_container_add (GTK_CONTAINER (scrolledwindow8), treeview1);

  scrolledwindow7 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow7);
  gtk_box_pack_start (GTK_BOX (hbox1), scrolledwindow7, TRUE, TRUE, 0);

  textview7 = gtk_text_view_new ();
  gtk_widget_show (textview7);
  gtk_container_add (GTK_CONTAINER (scrolledwindow7), textview7);

  label7 = gtk_label_new (_("Diff"));
  gtk_widget_show (label7);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook2), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook2), 0), label7);

  scrolledwindow4 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow4);
  gtk_container_add (GTK_CONTAINER (notebook2), scrolledwindow4);

  textview4 = gtk_text_view_new ();
  gtk_widget_show (textview4);
  gtk_container_add (GTK_CONTAINER (scrolledwindow4), textview4);

  label8 = gtk_label_new (_("Policy 1"));
  gtk_widget_show (label8);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook2), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook2), 1), label8);

  scrolledwindow5 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow5);
  gtk_container_add (GTK_CONTAINER (notebook2), scrolledwindow5);

  textview5 = gtk_text_view_new ();
  gtk_widget_show (textview5);
  gtk_container_add (GTK_CONTAINER (scrolledwindow5), textview5);

  label9 = gtk_label_new (_("Policy 2"));
  gtk_widget_show (label9);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook2), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook2), 2), label9);

  scrolledwindow6 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow6);
  gtk_container_add (GTK_CONTAINER (notebook2), scrolledwindow6);

  textview6 = gtk_text_view_new ();
  gtk_widget_show (textview6);
  gtk_container_add (GTK_CONTAINER (scrolledwindow6), textview6);

  label10 = gtk_label_new (_("Policy Stats"));
  gtk_widget_show (label10);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook2), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook2), 3), label10);

  g_signal_connect ((gpointer) Run_Diff, "activate",
                    G_CALLBACK (on_open1_activate),
                    NULL);
  g_signal_connect ((gpointer) Exit, "activate",
                    G_CALLBACK (on_quit1_activate),
                    NULL);
  g_signal_connect ((gpointer) Help, "activate",
                    G_CALLBACK (on_Help_activate),
                    NULL);
  g_signal_connect ((gpointer) about, "activate",
                    G_CALLBACK (on_about1_activate),
                    NULL);

  gtk_window_add_accel_group (GTK_WINDOW (window1), accel_group);

  return window1;
}

GtkWidget*
create_dialog1 (void)
{
  GtkWidget *dialog1;
  GtkWidget *dialog_vbox1;
  GtkWidget *vbox4;
  GtkWidget *hbox7;
  GtkWidget *entry4;
  GtkWidget *button6;
  GtkWidget *hbox8;
  GtkWidget *entry5;
  GtkWidget *button7;
  GtkWidget *dialog_action_area1;
  GtkWidget *cancelbutton1;
  GtkWidget *Diff;

  dialog1 = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (dialog1), _("dialog1"));
  gtk_window_set_type_hint (GTK_WINDOW (dialog1), GDK_WINDOW_TYPE_HINT_DIALOG);

  dialog_vbox1 = GTK_DIALOG (dialog1)->vbox;
  gtk_widget_show (dialog_vbox1);

  vbox4 = gtk_vbox_new (TRUE, 0);
  gtk_widget_show (vbox4);
  gtk_box_pack_start (GTK_BOX (dialog_vbox1), vbox4, FALSE, FALSE, 0);

  hbox7 = gtk_hbox_new (FALSE, 1);
  gtk_widget_show (hbox7);
  gtk_box_pack_start (GTK_BOX (vbox4), hbox7, FALSE, FALSE, 0);

  entry4 = gtk_entry_new ();
  gtk_widget_show (entry4);
  gtk_box_pack_start (GTK_BOX (hbox7), entry4, TRUE, TRUE, 0);
  gtk_entry_set_width_chars (GTK_ENTRY (entry4), 30);

  button6 = gtk_button_new_with_mnemonic (_("Browse"));
  gtk_widget_show (button6);
  gtk_box_pack_start (GTK_BOX (hbox7), button6, FALSE, FALSE, 0);

  hbox8 = gtk_hbox_new (FALSE, 1);
  gtk_widget_show (hbox8);
  gtk_box_pack_start (GTK_BOX (vbox4), hbox8, FALSE, FALSE, 0);

  entry5 = gtk_entry_new ();
  gtk_widget_show (entry5);
  gtk_box_pack_start (GTK_BOX (hbox8), entry5, TRUE, TRUE, 0);
  gtk_entry_set_width_chars (GTK_ENTRY (entry5), 30);

  button7 = gtk_button_new_with_mnemonic (_("Browse"));
  gtk_widget_show (button7);
  gtk_box_pack_start (GTK_BOX (hbox8), button7, FALSE, FALSE, 0);

  dialog_action_area1 = GTK_DIALOG (dialog1)->action_area;
  gtk_widget_show (dialog_action_area1);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area1), GTK_BUTTONBOX_END);

  cancelbutton1 = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_show (cancelbutton1);
  gtk_dialog_add_action_widget (GTK_DIALOG (dialog1), cancelbutton1, GTK_RESPONSE_CANCEL);
  GTK_WIDGET_SET_FLAGS (cancelbutton1, GTK_CAN_DEFAULT);

  Diff = gtk_button_new_with_mnemonic (_("Diff"));
  gtk_widget_show (Diff);
  gtk_dialog_add_action_widget (GTK_DIALOG (dialog1), Diff, GTK_RESPONSE_APPLY);
  GTK_WIDGET_SET_FLAGS (Diff, GTK_CAN_DEFAULT);

  g_signal_connect ((gpointer) button6, "clicked",
                    G_CALLBACK (on_browsep1_clicked),
                    NULL);
  g_signal_connect ((gpointer) button7, "clicked",
                    G_CALLBACK (on_browsep2_clicked),
                    NULL);
  g_signal_connect ((gpointer) cancelbutton1, "clicked",
                    G_CALLBACK (on_cancelbutton1_clicked),
                    NULL);
  g_signal_connect ((gpointer) Diff, "clicked",
                    G_CALLBACK (on_Diff_clicked),
                    NULL);


  return dialog1;
}

GtkWidget*
create_filechooserdialog1 (void)
{
  GtkWidget *filechooserdialog1;
  GtkWidget *dialog_vbox2;
  GtkWidget *dialog_action_area2;
  GtkWidget *button8;
  GtkWidget *button9;

  filechooserdialog1 = gtk_file_chooser_dialog_new (_("Open Policy 1"), NULL, GTK_FILE_CHOOSER_ACTION_OPEN, NULL);
  gtk_window_set_type_hint (GTK_WINDOW (filechooserdialog1), GDK_WINDOW_TYPE_HINT_DIALOG);

  dialog_vbox2 = GTK_DIALOG (filechooserdialog1)->vbox;
  gtk_widget_show (dialog_vbox2);

  dialog_action_area2 = GTK_DIALOG (filechooserdialog1)->action_area;
  gtk_widget_show (dialog_action_area2);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area2), GTK_BUTTONBOX_END);

  button8 = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_show (button8);
  gtk_dialog_add_action_widget (GTK_DIALOG (filechooserdialog1), button8, GTK_RESPONSE_CANCEL);
  GTK_WIDGET_SET_FLAGS (button8, GTK_CAN_DEFAULT);

  button9 = gtk_button_new_from_stock ("gtk-open");
  gtk_widget_show (button9);
  gtk_dialog_add_action_widget (GTK_DIALOG (filechooserdialog1), button9, GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (button9, GTK_CAN_DEFAULT);

  g_signal_connect ((gpointer) button8, "clicked",
                    G_CALLBACK (on_browsep1_cancel_clicked),
                    NULL);
  g_signal_connect ((gpointer) button9, "clicked",
                    G_CALLBACK (on_browsep1_open_clicked),
                    NULL);

  gtk_widget_grab_default (button9);
  return filechooserdialog1;
}

GtkWidget*
create_filechooserdialog2 (void)
{
  GtkWidget *filechooserdialog2;
  GtkWidget *dialog_vbox3;
  GtkWidget *dialog_action_area3;
  GtkWidget *button10;
  GtkWidget *button11;

  filechooserdialog2 = gtk_file_chooser_dialog_new (_("Open Policy 2"), NULL, GTK_FILE_CHOOSER_ACTION_OPEN, NULL);
  gtk_window_set_type_hint (GTK_WINDOW (filechooserdialog2), GDK_WINDOW_TYPE_HINT_DIALOG);

  dialog_vbox3 = GTK_DIALOG (filechooserdialog2)->vbox;
  gtk_widget_show (dialog_vbox3);

  dialog_action_area3 = GTK_DIALOG (filechooserdialog2)->action_area;
  gtk_widget_show (dialog_action_area3);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area3), GTK_BUTTONBOX_END);

  button10 = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_show (button10);
  gtk_dialog_add_action_widget (GTK_DIALOG (filechooserdialog2), button10, GTK_RESPONSE_CANCEL);
  GTK_WIDGET_SET_FLAGS (button10, GTK_CAN_DEFAULT);

  button11 = gtk_button_new_from_stock ("gtk-open");
  gtk_widget_show (button11);
  gtk_dialog_add_action_widget (GTK_DIALOG (filechooserdialog2), button11, GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (button11, GTK_CAN_DEFAULT);

  g_signal_connect ((gpointer) button10, "clicked",
                    G_CALLBACK (on_browsep2_cancel_clicked),
                    NULL);
  g_signal_connect ((gpointer) button11, "clicked",
                    G_CALLBACK (on_browsep2_open_clicked),
                    NULL);

  gtk_widget_grab_default (button11);
  return filechooserdialog2;
}

